# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys
sys.path.insert(0, os.path.abspath('./_extensions'))
sys.path.insert(0, os.path.abspath('./content'))

# -- Project information -----------------------------------------------------

project = 'Documentation Sphinx'
author = 'Yannick Chistel'
year = '2024'
copyright = year + ',' + author

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = ["sphinx_favicon",'sphinx_pyscript','numbered_title']

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'fr'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = ['nb']

# Dossier principal de la documentation
master_doc = 'index'

# -- Options for HTML output -------------------------------------------------
html_baseurl = 'https://ychistel.github.io/'
# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
#html_theme = 'alabaster'
html_theme = 'sphinx_book_theme'
#html_theme = 'pydata_sphinx_theme'
html_theme_options = {
    "home_page_in_toc" : True,
    "logo":{
        "alt_text":"Home",
        "text": "T.NSI"
    },
    "use_download_button": True,
    "icon_links": [
        {
            # Label for this link
            "name": "GitHub",
            # URL where the link will redirect
            "url": "https://github.com/<your-org>/<your-repo>",  # required
            # Icon class (if "type": "fontawesome"), or path to local image (if "type": "local")
            "icon": "fa-brands fa-square-github",
            # The type of image to be used (see below for details)
            "type": "fontawesome",
        }
    ],
    # Ajout d'une sidebar dans la navigation latérale
    "primary_sidebar_end": ["sites.html"]
}

# Définir des variables pour les utiliser avec les fichiers placés dans les templates
html_context = {
    'sites' : {
        'ENT Normandie' : 'https://www.l-educdenormandie.fr/',
        'Cours sur Github' : 'https://ychistel.github.io/cours/',
        'PyData Sphinx Thème' : 'https://pydata-sphinx-theme.readthedocs.io/en/stable/',
        'Sphinx Book Thème' : 'https://sphinx-book-theme.readthedocs.io/en/latest/index.html'
    }
}

# Ajout du logo et du favicon pour le site
html_logo = '_static/img/logo.svg'
favicons = [
    "img/favicon-16x16.png",
    "img/favicon-32x32.png",
]

#html_title = '<a href="https://ychistel.github.io/cours/content/1nsi.html">SPHINX</a>'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']

html_css_files = ['css/custom.css']

html_js_files = []


